ALTER TABLE `users` ADD `jail` INT NOT NULL DEFAULT '0';
ALTER TABLE `users` ADD `time` VARCHAR(255) NOT NULL DEFAULT '0';
ALTER TABLE `users` ADD `jail_reason` VARCHAR(255) NOT NULL DEFAULT 'Default';